name: golden_tester
description: A package to facilitate golden testing in Flutter.
version: 0.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  path_provider: ^2.0.9
  image: ^3.0.1
  collection: ^1.15.0
